---
title: "Organização"
output:
  pdf_document: default
  html_notebook: default
---

Limpeza de dados de armadilhas fotográficas PELD - CCM.

Desenvolvimento: Fernando Lima, D.Sc.

## PREPARAÇÃO

### PACOTES

```{r pacotes, message=FALSE}
rm(list = ls(all = TRUE))
source("../funcoes/pacotes.R")
pacotes("here", "readr", "dplyr", "stringr", "sf", "tibble")
```

### Carregar arquivos

```{r}
read_csv_file <- function(filename) {
  readr::read_csv(
    here(
      "01_dadosDeEntrada", filename
      ),
    show_col_types = FALSE
    )
}


read_csv_tab <- function(filename) {
  readr::read_delim(
    here(
      "01_dadosDeEntrada", filename
      ),
    delim = "\t",
    show_col_types = FALSE
    )
}


```


## Atlantic-Amphibians

```{r}
atlanticAmphibiansSites <- read_csv_file(
  "atlantic_amphibians/ATLANTIC_AMPHIBIANS_sites.csv"
  ) %>%
  select(
    id,
    latitude,
    longitude
    ) %>%
  filter(complete.cases(.))

atlanticAmphibiansSpecies <- read_csv_file(
  "atlantic_amphibians/ATLANTIC_AMPHIBIANS_species.csv"
  ) %>%
  select(
    id,
    valid_name
    ) %>%
  filter(complete.cases(.))

atlanticAmphibians <- atlanticAmphibiansSpecies %>%
  left_join(
    atlanticAmphibiansSites, by = "id"
    ) %>%
  rename(
    especie = valid_name
  )

atlanticAmphibiansReferences <- read_csv_file("atlantic_amphibians/ATLANTIC_AMPHIBIANS_references.csv")
```

## Cortar para área de interesse

```{r}

# options
options(timeout = 1e6)
sf::sf_use_s2(FALSE)
conexao <- sf::st_read(here("01_dadosDeEntrada/geo", "area_de_abrangencia1_cma_4674.shp"))
conexaoLogical <- as.logical(conexao)

atlanticAmphibiansConexao <-  atlanticAmphibians[conexao, ] %>% 
  tibble::rowid_to_column()

```
### Exportar arquivos `*.csv`

```{r}
readr::write_csv(atlanticAmphibians, here("03_dadosDeSaida", "atlanticAmphibians.csv"))
```

## Atlantic Ants

```{r}
atlanticAnts <- read_csv_tab(
  "atlantic_ants/ATLANTIC_ANTS_dataset.txt"
  ) %>%
  mutate(
  speciesName = paste(Genus, Species)
  ) %>%
  select(
    AANTS.code,
    speciesName,
    Latitude.y,
    Longitude.x
  ) %>%
   filter(complete.cases(.)
          ) %>%
  rename(
    id = AANTS.code,
    especie = speciesName,
    latitude = Latitude.y,
    longitude = Longitude.x
  )
```
### Exportar arquivos `*.csv`

```{r}
readr::write_csv(atlanticAnts, here("03_dadosDeSaida", "atlanticAnts.csv"))
```


## Atlantic Birds

```{r}
atlanticBirdsQualitative <- read_csv_file(
  "atlantic_birds/ATLANTIC_BIRDS_qualitative.csv"
  ) %>%
  filter(
    Year > 2003
    ) %>%
  select(
    Record_id,
    Species,
    Latitude_y,
    Longitude_x
    ) %>%
  filter(
    complete.cases(.)
    ) %>%
  rename(
    id = Record_id,
    especie = Species,
    latitude = Latitude_y,
    longitude = Longitude_x
  )

  
atlanticBirdsQuantitative <- read_csv_file(
  "atlantic_birds/ATLANTIC_BIRDS_quantitative.csv"
  )# %>%
  select(
    id,
    valid_name
    ) %>%
  filter(complete.cases(.))

atlanticAmphibians <- atlanticAmphibiansSpecies %>%
  left_join(
    atlanticAmphibiansSites, by = "id"
    )

atlanticAmphibiansReferences <- read_csv_file("atlantic_amphibians/ATLANTIC_AMPHIBIANS_references.csv")
```

```{r}
readr::write_csv(atlanticBirdsQualitative, here("03_dadosDeSaida", "atlanticBirdsQualitative.csv"))
```



### Integrar e organizar informações
```{r}
dados <- deployments %>%
  dplyr::left_join(
    sequences, by = "deployment_id"
    ) %>%
  # filtrar identificações a nível de espécie
  dplyr::filter(
    !is.na(species)
  ) %>%
  # juntar gênero e espécie para nome científico
  dplyr::mutate(
    especie = paste(genus, species),
    placename = substr(deployment_id, 1,4),
    subproject_name = str_replace(subproject_name, "PAISAGEM ", "L")
  ) %>%
  dplyr::rename(
          ID_Landscape = subproject_name,
          ID_SamplingPoint = placename
          ) %>%
  dplyr::select(
    ID_Landscape, ID_SamplingPoint, everything()
  )
```

```{r}
# Remove unwanted species
species_to_remove <- c(
  "Disparo falso",
  "Não identificado",
  "Disparo falso",
  "Não listado",
  "Chiroptera"
  )
timeLapse <- timeLapse[!timeLapse$Species %in% species_to_remove,]

# Extract IDs from RelativePath column
timeLapse <- timeLapse %>%
  mutate(
    ID_Landscape = substr(RelativePath, 1, 3),
    ID_SamplingPoint = substr(RelativePath, 4, 7)
  ) %>%
  select(ID_Landscape, ID_SamplingPoint, everything()
  )

sort(unique(timeLapse$Species))
```


```{r}
dados <- dados %>%
  # selecionar dados que o Miltinho pediu
  dplyr::select(
    subproject_name, placename,family,especie
    ) %>%
  # agrupar espécies e plotar número de registros
  dplyr::group_by(
    subproject_name, placename, family, especie
    ) %>%
  dplyr::summarise(
    n = n()
    ) %>%
  # filtrar registros não identificados
  dplyr::filter(
    especie != "No CV Result No CV Result"
    ) %>%
  # renomear
  dplyr::rename(
          ID_Paisagem = subproject_name,
          ID_Sitio = placename,
          Familia = family,
          Especie = especie,
          NuRegistros = n)

#checagem
sort(unique(dados$Especie))

sort(unique(dados$ID_Sitio))

dados$Especie <- gsub("Didelphis marsupialis","Didelphis aurita",
                          dados$Especie)

```

### Exportar arquivos `*.csv`

```{r}
readr::write_csv(dados, here("03_dadosDeSaida", "sinteseCamTrapsPELDCCM.csv"))
```
